asdf

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,4 +1,10 @@
 #!/usr/bin/env sh
 . "${0%/*}/h"
 requiredPattern="^(feat|fix|style|refactor|test|cd|docs|chore): .*$"
+if ! [[ $message =~ $requiredPattern ]];
+then
+    echo "Invalid commit message:"
+    echo "$message"
+    echo "It should look like \"fix: make image display properly\", see .husky/commit-msg"
+fi
 exit 1
